Repository cognitedata/cognite-sdk-python, pull requests merged in 2019-10, with the labels that each got.

#567 Fix raw list to pd.DataFrame conversion by handling missing vals and cols (#547)
  CHANGELOG.md
  cognite/client/data_classes/raw.py
  tests/tests_unit/test_api/test_raw.py
Labels: bug

#570 Release v1.3.1
  CHANGELOG.md
  cognite/client/__init__.py
Labels: 1.x

#572 dont retrieve metadata in to retrieve_dataframe
  CHANGELOG.md
  cognite/client/_api/datapoints.py
  tests/tests_unit/test_api/test_datapoints.py
Labels: auto-update

#574 Add .search() on RelationshipsAPI
  CHANGELOG.md
  cognite/client/_api/files.py
  cognite/client/_api/relationships.py
  cognite/client/data_classes/__init__.py
  cognite/client/data_classes/assets.py
  cognite/client/data_classes/events.py
  cognite/client/data_classes/files.py
  cognite/client/data_classes/relationships.py
  cognite/client/data_classes/sequences.py
  cognite/client/data_classes/time_series.py
  generate_from_spec.py
  openapi/tests/input_output/output.py
  openapi/tests/input_output/output_test.py
  tests/tests_unit/test_api/test_files.py
  tests/tests_unit/test_api/test_relationships.py
  tests/tests_unit/test_api/test_signatures.py
Labels: auto-update

#579 Snippets generator and documentation links
  cognite/client/_api/assets.py
  cognite/client/_api/datapoints.py
  cognite/client/_api/events.py
  cognite/client/_api/files.py
  cognite/client/_api/iam.py
  cognite/client/_api/login.py
  cognite/client/_api/raw.py
  cognite/client/_api/sequences.py
  cognite/client/_api/three_d.py
  cognite/client/_api/time_series.py
  generate_documentation_snippets.py
Labels: auto-update

#573 Change CogniteUpdate to merge instead of overwrite for ._add() and ._remove()
  CHANGELOG.md
  cognite/client/data_classes/_base.py
  tests/tests_unit/test_api/test_assets.py
  tests/tests_unit/test_api/test_events.py
  tests/tests_unit/test_api/test_files.py
  tests/tests_unit/test_api/test_sequences.py
  tests/tests_unit/test_api/test_time_series.py
  tests/tests_unit/test_base.py
Labels: auto-update

#568 refactor datapoints and fix bugs in include_outside_points
  CHANGELOG.md
  cognite/client/_api/datapoints.py
  tests/tests_integration/test_api/test_datapoints.py
  tests/tests_unit/test_api/test_datapoints.py
Labels: auto-update
