Repository cognitedata/cognite-sdk-python, pull requests merged in 2020-11, with the labels that each got.

#743 implement geoLocation in files
  cognite/client/_api/files.py
  cognite/client/data_classes/__init__.py
  cognite/client/data_classes/files.py
  cognite/client/data_classes/shared.py
  tests/tests_integration/test_api/test_files.py
  tests/tests_unit/test_api/test_files.py
Labels: auto-merge, auto-update

#752 Delete created group in integration test
  tests/tests_integration/test_api/test_iam.py
Labels: auto-merge

#751 [CDF-8955] Remove redundant example from Asset update
  cognite/client/_api/assets.py
Labels: auto-merge

#754 Fix typo in example
  cognite/client/_api/sequences.py
Labels: auto-merge, auto-update

#755 Remove python v3.6, v3.7 from test_and_build
  .github/workflows/test_and_build.yml
Labels: auto-merge, auto-update

#757 [CDF-8371] Allow resource metadata update using .metadata.set(None)
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api/assets.py
  cognite/client/_api_client.py
  tests/tests_integration/test_api/test_assets.py
  tests/tests_integration/test_api/test_events.py
  tests/tests_integration/test_api/test_sequences.py
  tests/tests_integration/test_api/test_time_series.py
Labels: auto-merge, auto-update

#760 fix retry bug
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_http_client.py
Labels: auto-merge, auto-update

#763 [COREAPI-16] Move Relationships to release Python SDK
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_cognite_client.py
  cognite/client/beta.py
Labels: auto-update

#758 entity matching to beta client
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api/entity_matching.py
  cognite/client/_api_client.py
  cognite/client/beta.py
  cognite/client/data_classes/__init__.py
  cognite/client/data_classes/contextualization.py
  cognite/client/exceptions.py
  cognite/client/utils/_auxiliary.py
  docs/source/cognite.rst
  generate_code_snippets.py
  tests/tests_integration/test_api/test_data_sets.py
  tests/tests_integration/test_api/test_entity_matching.py
  tests/tests_unit/test_api/test_data_sets.py
  tests/tests_unit/test_api/test_entity_matching.py
  tests/tests_unit/test_data_classes/test_assets.py
  tests/tests_unit/test_data_classes/test_generated.py
  tests/tests_unit/test_data_classes/test_repr.py
Labels: auto-update

#765 Move relationships to release in docs and remove model hosting
  docs/source/cognite.rst
Labels: auto-merge, auto-update
