Repository cognitedata/cognite-sdk-python, pull requests merged in 2020-08, with the labels that each got.

#715 Docs fix for events.aggregate_unique_values
  cognite/client/_api/events.py
Labels: auto-merge, auto-update, documentation

#716 Fix for new pandas v1.1.0 behaviour of DataFrame.interpolate to throw…
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api/datapoints.py
Labels: auto-merge, auto-update, bug

#720 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: auto-merge, auto-update

#721 Update Codeowners to Core API
  .github/CODEOWNERS
Labels: auto-merge, auto-update

#719 add playground to retryable endpoints
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api_client.py
  tests/tests_unit/test_api_client.py
Labels: auto-merge, auto-update

#725 Add timeseries list to retryable endpoints
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api_client.py
  tests/tests_unit/test_api_client.py
Labels: auto-merge, auto-update
