Repository cognitedata/cognite-sdk-python, pull requests merged in 2021-07, with the labels that each got.

#833 Add filter3dNodes endpoint
  CHANGELOG.md
  cognite/client/_api/three_d.py
  cognite/client/_version.py
  docs/source/cognite.rst
  tests/tests_unit/test_api/test_3d.py
Labels: auto-merge

#834 Adding set labels in Python SDK
  CHANGELOG.md
  cognite/client/data_classes/_base.py
  cognite/client/data_classes/assets.py
  tests/tests_unit/test_api/test_assets.py
Labels: auto-update

#836 Release 2.26.0
  CHANGELOG.md
  cognite/client/_version.py
  tests/tests_integration/test_api/test_entity_matching.py
Labels: auto-merge, auto-update

#835 Add PR template
  .github/pull_request_template.md
Labels: auto-merge, auto-update
