Repository cognitedata/cognite-sdk-python, pull requests merged in 2021-03, with the labels that each got.

#793 CDF-11202 Move entity matching from beta to v1.
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api/three_d.py
  cognite/client/_cognite_client.py
  cognite/client/_http_client.py
  cognite/client/beta.py
  cognite/client/data_classes/assets.py
  cognite/client/data_classes/labels.py
  cognite/client/data_classes/relationships.py
  tests/tests_integration/test_api/test_entity_matching.py
  tests/tests_integration/test_api/test_synthetic_time_series.py
  tests/tests_unit/test_api/test_assets.py
  tests/tests_unit/test_api/test_datapoints.py
  tests/tests_unit/test_api/test_events.py
  tests/tests_unit/test_api/test_labels.py
  tests/tests_unit/test_api/test_synthetic_time_series.py
  tests/tests_unit/test_utils/test_auxiliary.py
Labels: auto-update

#790 Clean up issue templates
  .github/ISSUE_TEMPLATE/bug-report--1-x-x-.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request--1-x-x-.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: auto-merge, auto-update

#794 Fix CogniteMissingClientError being raised on relationship.create failure.
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api_client.py
  cognite/client/utils/_concurrency.py
  tests/tests_integration/test_api/test_relationships.py
Labels: auto-merge, auto-update, bug

#795 Add List 3D Nodes query parameters
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/_api/three_d.py
  cognite/client/_api_client.py
  tests/tests_integration/test_api/test_three_d.py
Labels: auto-update

#799 Move entity matching documentation from experimental
  docs/source/cognite.rst
Labels: auto-merge, auto-update

#800 Implement support for createdTime on raw dbs and tables
  CHANGELOG.md
  cognite/client/__init__.py
  cognite/client/data_classes/raw.py
Labels: auto-merge, auto-update

#802 [CDF-11405] Only treat 200/201/202 as successfull response
  cognite/client/_api_client.py
  tests/tests_integration/test_cognite_client.py
Labels: auto-update

#807 [CDF-11424] Add tests for downloading an empty file
  tests/tests_integration/test_api/test_files.py
Labels: auto-merge, auto-update

#806 [CDF-11459] Ignore any exceptions from pypi check. also reduce timeout.
  cognite/client/utils/_client_config.py
  cognite/client/utils/_version_checker.py
  tests/tests_unit/test_cognite_client.py
Labels: auto-merge, auto-update

#804 [CDF-11440] Add security_categories to files.upload/upload_bytes docstrings
  cognite/client/_api/files.py
Labels: auto-merge, auto-update

#803 [CDF-11407] Support using proxies
  cognite/client/_api_client.py
  cognite/client/_cognite_client.py
  cognite/client/utils/_client_config.py
Labels: auto-merge, auto-update

#808 Remove py.typed
  cognite/client/py.typed
Labels: auto-merge, auto-update

#805 [CDF-11456] Override default create limit for datasets - set to 10
  cognite/client/_api/data_sets.py
Labels: auto-merge, auto-update

#809 Release: 2.17.0
  CHANGELOG.md
  cognite/client/__init__.py
Labels: auto-merge, auto-update
