Repository cognitedata/cognite-sdk-python, pull requests merged in 2022-06, with the labels that each got.

#935 improve geospatial tests
  tests/tests_integration/test_api/test_geospatial.py
Labels: auto-update, auto-merge

#936 Revert "Reduce request multiple timeseries (#917)"
  .github/CODEOWNERS
  .github/workflows/release.yaml
  .github/workflows/test_and_build.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  README.md
  cognite/client/_api/datapoints.py
  cognite/client/_api/files.py
  cognite/client/_api/geospatial.py
  cognite/client/_http_client.py
  cognite/client/_version.py
  cognite/client/data_classes/datapoints.py
  cognite/client/utils/_auxiliary.py
  tests/tests_integration/test_api/test_geospatial.py
  tests/tests_integration/test_api/test_transformations/test_schema.py
  tests/tests_integration/test_api/test_transformations/test_transformations.py
  tests/tests_unit/test_api/test_datapoints.py
  tests/tests_unit/test_utils/test_time.py
  tox.ini
Labels: auto-update, auto-merge

#928 [VIS-849] Feat: Add support for Annotations API
  CHANGELOG.md
  cognite/client/_api/annotations.py
  cognite/client/_cognite_client.py
  cognite/client/data_classes/__init__.py
  cognite/client/data_classes/annotations.py
  docs/source/cognite.rst
  tests/tests_integration/test_api/test_annotations.py
  tests/tests_unit/test_data_classes/test_annotations.py
Labels: auto-update

#934 [CXT-608] move diagrams to stable
  CHANGELOG.md
  cognite/client/_api/diagrams.py
  cognite/client/_cognite_client.py
  cognite/client/_version.py
  cognite/client/data_classes/contextualization.py
  docs/source/cognite.rst
  tests/tests_integration/test_api/test_diagrams.py
Labels: auto-merge

#946 quick fix for the create CRS example
  cognite/client/_api/geospatial.py
Labels: auto-update, auto-merge
