Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-06, with the labels that each got.

#2163 Maintain datatype retrieve rows
  CHANGELOG.md
  cognite/client/_api/raw.py
  cognite/client/_version.py
  pyproject.toml
  tests/tests_unit/test_api/test_raw.py
  tests/utils.py
Labels: risk-review-ongoing, waiting-for-team

#2175 Add capability AppConfigAcl
  CHANGELOG.md
  cognite/client/_version.py
  cognite/client/data_classes/capabilities.py
  pyproject.toml
  tests/tests_unit/test_data_classes/test_capabilities.py
Labels: risk-review-mentor, risk-review-ongoing, waiting-for-team

#2165 Add argument to use instance IDs as column names in insert dataframe
  CHANGELOG.md
  cognite/client/_api/datapoints.py
  cognite/client/_version.py
  pyproject.toml
  tests/tests_unit/test_api/test_datapoints.py
Labels: risk-review-ongoing, waiting-for-team

#2170 feat(agents): addition of data classes in preparation for adding agents support
  cognite/client/data_classes/agents/__init__.py
  cognite/client/data_classes/agents/agent_tools.py
  cognite/client/data_classes/agents/agents.py
  tests/tests_unit/test_data_classes/test_agents/test_agent_tools.py
  tests/tests_unit/test_data_classes/test_agents/test_agents.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-team
