Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-04, with the labels that each got.

#2139 Add support for simulator routine revisions
  CHANGELOG.md
  cognite/client/_api/simulators/models_revisions.py
  cognite/client/_api/simulators/routine_revisions.py
  cognite/client/_api/simulators/routines.py
  cognite/client/data_classes/simulators/filters.py
  cognite/client/data_classes/simulators/routine_revisions.py
  cognite/client/data_classes/simulators/simulators.py
  cognite/client/testing.py
  tests/tests_integration/test_api/test_simulators/conftest.py
  tests/tests_integration/test_api/test_simulators/seed/data.py
  tests/tests_integration/test_api/test_simulators/test_integrations.py
  tests/tests_integration/test_api/test_simulators/test_routine_revisions.py
  tests/tests_unit/test_docstring_examples.py
  tests/utils.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr

#2142 clean up postgres gateway api and acls
  CHANGELOG.md
  cognite/client/_api/postgres_gateway/tables.py
  cognite/client/_api/postgres_gateway/users.py
  cognite/client/_version.py
  cognite/client/data_classes/capabilities.py
  pyproject.toml
  tests/tests_integration/test_api/test_extraction_pipelines.py
  tests/tests_unit/test_data_classes/test_capabilities.py
Labels: risk-review-ongoing

#2146 [Functions] Fix type annotations for generic types
  CHANGELOG.md
  cognite/client/_api/functions.py
Labels: risk-review-ongoing

#2147 Fix typing of DatapointSubscription.time_series_count
  CHANGELOG.md
  cognite/client/_version.py
  cognite/client/data_classes/datapoints_subscriptions.py
  pyproject.toml
  tests/tests_unit/test_data_classes/test_datapoint_subscriptions.py
Labels: risk-review-done

#2150 fix response assertion in data modeling tests
  tests/tests_integration/test_api/test_data_modeling/test_spaces.py
Labels: risk-review-ongoing, waiting-for-team
