Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-09, with the labels that each got.

#2228 feat: add pandas DataFrame conversion methods to SimulatorRoutineRevisionCore
  CHANGELOG.md
  cognite/client/data_classes/simulators/routine_revisions.py
  pyproject.toml
  tests/tests_unit/test_data_classes/test_simulators.py
Labels: waiting-for-team

#2254 fixed formatting issue for many entries
  cognite/client/_api/entity_matching.py
  cognite/client/_api/functions.py
  cognite/client/_api/templates.py
  cognite/client/data_classes/_base.py
  cognite/client/data_classes/data_modeling/cdm/v1.py
  cognite/client/data_classes/data_modeling/instances.py
  cognite/client/data_classes/geospatial.py
  cognite/client/data_classes/workflows.py
  cognite/client/utils/_pyodide_helpers.py
Labels: risk-review-ongoing, waiting-for-team

#2317 chore: Update docstrings to include py312
  cognite/client/_api/functions.py
  cognite/client/data_classes/functions.py
Labels: risk-review-ongoing, waiting-for-team

#2335 chore: Update renovate
  renovate.json
Labels: risk-review-ongoing, waiting-for-team

#2308 chore(master): release 7.84.0
  CHANGELOG.md
  cognite/client/_version.py
  pyproject.toml
Labels: autorelease: pending

#2341 fix: do not throw UserWarning from SDK code
  cognite/client/_api/data_modeling/instances.py
  cognite/client/_api/documents.py
  cognite/client/_api_client.py
  cognite/client/data_classes/data_modeling/query.py
  cognite/client/data_classes/data_modeling/views.py
  pytest.ini
  tests/tests_unit/test_data_classes/test_data_models/test_filters.py
Labels: waiting-for-risk-review

#2338 chore(master): release 7.85.0
  CHANGELOG.md
  cognite/client/_version.py
  pyproject.toml
Labels: autorelease: pending
