Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-07, with the labels that each got.

#2199 Skip flaky test
  tests/tests_integration/test_api/test_files.py
  tests/tests_integration/test_api/test_transformations/test_jobs.py
Labels: waiting-for-risk-review

#2198 MyPy pass on windows
  tests/tests_unit/test_utils/test_time.py
Labels: risk-review-ongoing, waiting-for-team

#2197 Gemini config and style guide
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: risk-review-ongoing, waiting-for-team

#2148 fix(simulators): Consistency for filtering
  cognite/client/_api/simulators/integrations.py
  cognite/client/_api/simulators/models.py
  cognite/client/_api/simulators/models_revisions.py
  cognite/client/data_classes/simulators/filters.py
  tests/tests_integration/test_api/test_simulators/conftest.py
  tests/tests_integration/test_api/test_simulators/test_integrations.py
  tests/tests_integration/test_api/test_simulators/test_models.py
Labels: risk-review-ongoing, waiting-for-team

#2196 feat: using agents data classes in new CRUD API
  CHANGELOG.md
  cognite/client/_api/agents/__init__.py
  cognite/client/_api/agents/agents.py
  cognite/client/_api_client.py
  cognite/client/_cognite_client.py
  cognite/client/_version.py
  cognite/client/data_classes/agents/agent_tools.py
  cognite/client/testing.py
  docs/source/agents.rst
  docs/source/index.rst
  pyproject.toml
  tests/tests_integration/test_api/test_agents.py
  tests/tests_unit/test_api/test_agents.py
  tests/utils.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-risk-review

#2205 [CDF-25306]🤖 Add AgentsAcl
  CHANGELOG.md
  cognite/client/_version.py
  cognite/client/data_classes/capabilities.py
  pyproject.toml
  tests/tests_unit/test_data_classes/test_capabilities.py
Labels: risk-review-ongoing, waiting-for-risk-review

#2173 [POFSP-1033] Simulator Integration docs & consistency fixes
  CHANGELOG.md
  cognite/client/_api/simulators/__init__.py
  cognite/client/_api/simulators/integrations.py
  cognite/client/_api/simulators/logs.py
  cognite/client/_api/simulators/models.py
  cognite/client/_api/simulators/models_revisions.py
  cognite/client/_api/simulators/routine_revisions.py
  cognite/client/_api/simulators/routines.py
  cognite/client/_api/simulators/runs.py
  cognite/client/_version.py
  cognite/client/data_classes/simulators/logs.py
  cognite/client/data_classes/simulators/models.py
  cognite/client/data_classes/simulators/routine_revisions.py
  cognite/client/data_classes/simulators/routines.py
  cognite/client/data_classes/simulators/runs.py
  cognite/client/data_classes/simulators/simulators.py
  docs/source/index.rst
  docs/source/simulators.rst
  pyproject.toml
  tests/tests_integration/test_api/test_simulators/conftest.py
  tests/tests_integration/test_api/test_simulators/test_integrations.py
  tests/tests_integration/test_api/test_simulators/test_models.py
  tests/tests_integration/test_api/test_simulators/test_runs.py
Labels: waiting-for-team

#2220 Some improvements to workflow/functions tests
  tests/tests_integration/test_api/test_functions.py
  tests/tests_integration/test_api/test_workflows.py
Labels: waiting-for-risk-review
