Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-10, with the labels that each got.

#2349 fix(agents): replace agentId with agentExternalId in chat API
  cognite/client/_api/agents/agents.py
  cognite/client/data_classes/agents/chat.py
  tests/tests_integration/test_api/test_agents.py
  tests/tests_unit/test_api/test_agents_chat.py
Labels: risk-review-ongoing, waiting-for-team

#2345 chore(master): release 7.86.0
  CHANGELOG.md
  cognite/client/_version.py
  pyproject.toml
Labels: autorelease: pending

#2339 feat(simulators): Add support for running simulations using revisions
  cognite/client/_api/simulators/routines.py
  cognite/client/data_classes/simulators/runs.py
  tests/tests_integration/test_api/test_simulators/test_routines.py
  tests/tests_integration/test_api/test_simulators/test_runs.py
  tests/tests_unit/test_data_classes/test_simulators.py
  tests/utils.py
Labels: waiting-for-risk-review, waiting-for-team
