Repository cognitedata/cognite-sdk-python, pull requests merged in 2025-08, with the labels that each got.

#2223 feat(simulators): filtering consistency in __call__ methods
  CHANGELOG.md
  cognite/client/_api/simulators/integrations.py
  cognite/client/_api/simulators/models.py
  cognite/client/_api/simulators/models_revisions.py
  cognite/client/_version.py
  pyproject.toml
  tests/tests_integration/test_api/test_simulators/test_integrations.py
  tests/tests_integration/test_api/test_simulators/test_models.py
Labels: risk-review-ongoing, waiting-for-team

#2238 feat(documents-api): add content, status, and passages endpoints to retryable list
  cognite/client/_api_client.py
Labels: risk-review-ongoing, waiting-for-risk-review

#2258 add runtime warning when changing `max_workers` has no effect
  cognite/client/utils/_concurrency.py
Labels: risk-review-ongoing, waiting-for-team

#2235 docs: updated example to include sources for instances.list and one with to_pandas
  cognite/client/_api/data_modeling/instances.py
Labels: risk-review-ongoing, waiting-for-team

#2218 feat(simulators): Add support for external dependencies
  CHANGELOG.md
  cognite/client/_api/simulators/models_revisions.py
  cognite/client/_version.py
  cognite/client/data_classes/simulators/models.py
  cognite/client/data_classes/simulators/simulators.py
  pyproject.toml
  tests/tests_integration/test_api/test_simulators/conftest.py
  tests/tests_integration/test_api/test_simulators/seed/ExtDependency.xml
  tests/tests_integration/test_api/test_simulators/seed/data.py
  tests/tests_integration/test_api/test_simulators/test_models.py
  tests/tests_unit/test_data_classes/test_simulators.py
Labels: risk-review-ongoing, waiting-for-team

#2227 Fix naming inconsistencies in simulators run namespace
  CHANGELOG.md
  cognite/client/_api/simulators/runs.py
  cognite/client/_version.py
  cognite/client/data_classes/simulators/__init__.py
  cognite/client/data_classes/simulators/runs.py
  pyproject.toml
Labels: risk-review-mentor, risk-review-ongoing

#2262 test(integration): fix simulator object seed (attempt 2)
  tests/tests_integration/test_api/test_simulators/conftest.py
Labels: risk-review-ongoing, waiting-for-team

#2226 Add "run_time" and "simulation_time" to automatic timestamp conversion fields
  CHANGELOG.md
  cognite/client/_version.py
  cognite/client/utils/_time.py
  pyproject.toml
  tests/tests_unit/test_utils/test_time.py
Labels: risk-review-ongoing, waiting-for-team

#2245 chore(simulators): Convert resource name seeder to dataclass
  tests/tests_integration/test_api/test_simulators/conftest.py
  tests/tests_integration/test_api/test_simulators/seed/data.py
  tests/tests_integration/test_api/test_simulators/test_integrations.py
  tests/tests_integration/test_api/test_simulators/test_models.py
  tests/tests_integration/test_api/test_simulators/test_routine_revisions.py
  tests/tests_integration/test_api/test_simulators/test_routines.py
  tests/tests_integration/test_api/test_simulators/test_runs.py
Labels: risk-review-ongoing, waiting-for-team

#2270 update docs and raise more meaningful errors for upload_content.
  CHANGELOG.md
  cognite/client/_api/files.py
  cognite/client/_version.py
  pyproject.toml
  tests/tests_integration/test_api/test_files.py
Labels: risk-review-mentor, risk-review-ongoing, waiting-for-risk-review

#2200 feat(CDF-19308): Add timezone as an optional param to WorkflowScheduledTriggerRule
  CHANGELOG.md
  cognite/client/_api/workflows.py
  cognite/client/_version.py
  cognite/client/data_classes/workflows.py
  pyproject.toml
  tests/tests_integration/test_api/test_workflows.py
  tests/utils.py
Labels: risk-review-ongoing, waiting-for-team

#2289 feat(agents): update agents SDK to use beta API
  CHANGELOG.md
  cognite/client/_api/agents/agents.py
  cognite/client/_version.py
  pyproject.toml
Labels: risk-review-ongoing, waiting-for-team
